# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 7.0


  before_script:
    - composer update
    - cp .env.example .env
    - php api project create mobi
    - php api service create mobi:stk